### ISSUE TITLE
Shorten Subject primary key length

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-animal#14]
In a meeting about another project, @dimitri-yatsenko commented that varchar(32) was longer than it should be for a primary key across the whole framework. Some documentation suggests limiting this value to 8 characters, if possible. Should the element reflect that?

`subject: varchar(8)`

Is there a process for determining backwards compatibility for existing use cases?

**Comment by dimitri-yatsenko** [comment]
yes please. Some fields propagate down to every element, including cells, model fits, etc. These should be short ids.

**Comment by kabilar** [comment]
Thanks @CBroz1.  I agree with this decision.  We do not currently have a process for determining backwards compatibility but this would be a good opportunity for creating such a process.  We can document the process in [Issue #22](https://github.com/datajoint/datajoint-elements/issues/22).
