### ISSUE TITLE
Naming uniformity: `element-animal` -> `element-subject` ?

### ISSUE THREAD

**Issue by CBroz1** [datajoint/element-animal#15]
Other elements are named after their respective primary tables (e.g., `lab.Lab` and `session.Session`). `element-animal` stands out as unique with `subject.Subject`. The language might also be a minor roadblock for future human-subjects researchers.

**Comment by CBroz1** [comment]
Making this changes would be broad in scope across elements, with many small edits across almost all existing workflows. Holding off pending discussion of the best timing for this change.

**Comment by kabilar** [comment]
Thanks @CBroz1.  Good catch.  For human subjects, what do you think would be the best naming scheme for the package, schema, and tables?

**Comment by CBroz1** [comment]
To use for human subjects, several tables would become unnecessary (e.g., `Cage`, `SubjectCullMethod`). Long term (i.e., U24 Year 3+), I think we could develop an alternate element or schema within the current element with more human-relevant tables, such as medical history. In the short term, I think we should preserve consistency of mapping element name to element primary table.

**Comment by kabilar** [comment]
That sounds good.  I do not think that this will cause backwards incompatibility requiring a migration script ([Issue #22](https://github.com/datajoint/datajoint-elements/issues/22)).

**Comment by ttngu207** [comment]
I'm good with this change

**Comment by kabilar** [comment]
Thanks all.  I will make the updates today for `element-animal` to `element-subject`, and will submit for @CBroz1's review.  Then we can rename the repository on GitHub.

**Comment by kabilar** [comment]
We will also need to modify this package on [pypi](https://pypi.org/project/element-animal/).

@CBroz1, could you please reach out to Raphael to determine who has the credentials and how to do this?

**Comment by CBroz1** [comment]
> modify this package on [pypi](https://pypi.org/project/element-animal/).

@kabilar just met with Raphael who suggested the following as our release process
1. Confirm new name availability ✅  and within-team consensus (flag for Dimitri?)
2. Issue one more release on old name, inclusive of a readme doc warning disclaimer pointing to the new one. In our current case, this can be a separate PR before merging the outstanding one.
3. Issue an internal engineering request ticket for Drew (on this first occasion, also include Raphael)

Note: PyPi releases cannot be pulled back only flagged as 'bad' while issuing another.

**Comment by kabilar** [comment]
Thanks @CBroz1.

1. @dimitri-yatsenko, we are confirming the package name change from `element-animal` to `element-subject`.
2. Will submit new pull requests today.
3. Once confirmed by Dimitri, please submit the internal ticket for `element-subject`.  We will not be releasing `element-interface` on pypi at the present time.

**Comment by CBroz1** [comment]
The decision was made to preserve the current naming scheme, [discussed here](https://github.com/datajoint/element-animal/pull/17#issuecomment-1012243976).
