### ISSUE TITLE
Add species to `subject_to_nwb` function

### ISSUE THREAD

**Issue by kabilar** [datajoint/element-animal#21]
- DANDI will soon be requiring NWB files to include species information.
- Add a condition to only include if not null.
- Consider enforcement around latin naming.

**Comment by CBroz1** [comment]
[These solutions](https://bioinformatics.stackexchange.com/questions/9312/python-module-for-fetching-ncbi-id-for-a-list-of-species) for fetching taxonomy IDs seems overkill for fetching latin names. Instead, we might embed a list of most common subject species in the element and throw a warning for items in that list when triggering the export. That list would be easy to expand if we asked users to submit git issues and could track number of unique species as an adoption metric.
