### ISSUE TITLE
Add contribution guidelines, code of conduct, issue templates

### ISSUE THREAD

**Issue by kabilar** [datajoint/element-animal#5]
- Mirror the [datajoint/pharus](https://github.com/datajoint/pharus) repository, once it is updated based off of today's discussion.
  ```
  /.github/ISSUE_TEMPLATE/bug_report.md
  /.github/ISSUE_TEMPLATE/feature_request.md
  /.github/ISSUE_TEMPLATE/config.yml
  /CONTRIBUTING.md
  /CODE_OF_CONDUCT.md
  ```

**Comment by CBroz1** [comment]
I'm not seeing a Code of Conduct in [datajoint/pharus](https://github.com/datajoint/pharus), not on the [datajoint-python](https://github.com/datajoint/datajoint-python) or [datajoint-elements](https://github.com/datajoint/datajoint-elements) repos. Should we develop one based on [github's template](https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md)?

**Comment by kabilar** [comment]
Thanks @CBroz1.  Good catch.  Yes, I agree.  Let's use the template you linked and we can fill in the email address in the `Enforcement` section.

@dimitri-yatsenko @guzman-raphael @ttngu207, would the Code of Conduct that Chris linked above work for all of our open-source software repositories?  Thank you.
